CSF Express-22 by Grade/Student Age Analysis
code-dot-org/analytics-infrastructure pull request #35
Opened 2023-06-29 19:19 UTC by jordan-springer

2023-06-30 18:37 UTC, bakerfranke requested changes

2023-06-30 18:37 UTC, bakerfranke commented on analysis/csf_express_22_by_student_grade.sql
> +            split_part(sections.grade,',',len(sections.grade)) as min_grade,
Two issues: 

1. You've symantically transposed min_grade and max_grade.  you want min_grade grabbing the first element of the list, and max grabbing the last.  You have the opposite, which will affect grade-band categories down the road.

2. This is returning NULL for min_grade (which should be max_grade) for **all record**s *with a comma*.  The reason is the length of the string includes all the commas.  So if grade = '7,8,9,10'. You want max grade to be element 4 of this list but the length of the string is 7 and there is no 7th element.

I don't think there is a way to do this using the string length.  you get the length of the array after splitting but that code would look ugly.  In my code I got around this by reversing the string, splitting it into an array, grabbing the first element, and then reversing that element since it would come out backwards.  This is a hack I learned to get around the fact that redshift SQL doest allow you to use -1 as an array index.

This sequence traces the effect:

1.SELECT **reverse('7,8,9,10');**
2.SELECT **split_part**(reverse('7,8,9,10'),**',',1)**;
3.SELECT **reverse**(split_part(reverse('7,8,9,10'),',',1));

The output of that is:
1. 01,9,8,7
2. 01
3. 10

2023-06-30 18:37 UTC, bakerfranke commented on analysis/csf_express_22_by_student_grade.sql
> +                when min_grade in ('K','1','2','3','4','5')
I'd expect a 9-12 grade band in here to match the output of method 1.

2023-07-01 01:55 UTC, jordan-springer commented on analysis/csf_express_22_by_student_grade.sql
> +            split_part(sections.grade,',',len(sections.grade)) as min_grade,
Great catches! Will get these resolved.

2023-07-01 01:56 UTC, jordan-springer commented on analysis/csf_express_22_by_student_grade.sql
> +                when min_grade in ('K','1','2','3','4','5')
🤦🏽

2023-07-01 13:03 UTC, bakerfranke approved these changes
Looks good.  Ship it!

2023-07-02 00:29 UTC, merged